### PR TITLE
New Context data workflow

### LINKED ISSUE #295: Display Context configuration list and detailed view
@romone22 commented on [Thu Jan 21 2021](https://github.com/Jarvis-Platform/jarvis-manager/issues/56)

Context is a new configuration type used to define parameters used by a configuration when it is deployed. 

Here is a example of context configuration : 

```
{
	"version": 2,
	"configuration_type": "context",
	"configuration_id": "context_dev",
	"environment": "DEV",
	"account": "000099",
	"activated": true,
	"archived": false,
	"parameters": {
		"test_integer": {
			"value": 123456,
			"type": "integer",
			"resource": "value",
			"description": "Some random value"
		},
		"test_float": {
			"value": 123456.7891,
			"type": "float",
			"resource": "value",
			"description": "Some random value"
		},
		"test_boolean": {
			"value": true,
			"type": "boolean",
			"resource": "value",
			"description": "Some random value"
		},
		"gcp_project_id_exc": {
			"value": "fd-io-jarvis-demo-exc",
			"type": "string",
			"resource": "gcp_project_id",
			"description": "The Default Exchange GCP Project ID. Example : fd-io-jarvis-demo-exc"
		},

		"gcs_source_bucket_n_in": {
			"value": "fd-io-exc-demo-n-in",
			"type": "string",
			"resource": "gcs_bucket",
			"description": "The Default Exchange Source IN Bucket ID. example: fd-io-exc-demo-n-in"
		},

		"gcp_credentials_secret_source_n_in": {
			"value": {
				"cipher_aes": "f168a80f4a21290b9537",
				"ciphertext": "6cfbb3e0586034b9ed94cbea01902ae7ca6c6aa5435fb1cee20680b4564eae60de210564aa2deaef2a7d397cc124ad78c80cd5a8afe1b2e626a3e07643d9c130ac80824e7622edeaeebbd9eafcf96b3509e1b9118e687f62a2cb1e0f15811ca4e1a86fe76566fef4bcc5f6a6d0b55303fb4e951c4a0b8d91e61bf83787ae3b4f91765a61747108b7cf8b5a8b7c309e9d403810b6b78adfc08cd3d7e79002a77e4930952377532cc516d9fb2fae0afc9debd68c7111199fd612f40cf4945b80fc36b648f8f259b96ccce9868f47b37477de152c46b3dc29b7d6616e8de3aff08879726739f9b4c42313023dd3664239cd6cdca4d7c2e24d4feb43cbb1a792197c86cac7ec8ffe34f309641f582e36d90468",
				"enc_session_key": "784b299e4c2e647ee60f11fdb48ea8f389821287ebc4d40dd17c59fed4f7a44d3b07c6e874fa9175f997634c7af5789708a5b178a571948620c93c2a281ec6aafd743823839ab",
				"tag": "f855cd875160c50e5bff3c8c49951227"
			},
			"type": "object",
			"resource": "gcp_credentials_secret",
			"description": "The GCP Credential use to load data from the gcp_credentials_secret_source_n_in bucket"
		},

		"gcp_project_id_dlk": {
			"value": "fd-io-jarvis-demo-dlk",
			"type": "string",
			"resource": "gcp_project_id",
			"description": "The Default Exchange GCP Project ID. Example : fd-io-jarvis-demo-dlk"
		},

		"gcs_mirror_bucket_n_in": {
			"value": "mirror-fd-io-demo-n-in",
			"type": "string",
			"resource": "gcs_bucket",
			"description": "The Default Exchange Mirror IN Bucket ID. Example : mirror-fd-io-demo-n-in"
		},

		"gcp_credentials_secret_mirror_n_in": {
			"value": {
				"cipher_aes": "f168a80f4a2d43280d90b9537",
				"ciphertext": "6cfbb3e0586034be6650201902ae7ca6c6aa5435fb1cee20680b4564eae60de210564aa2deaef2a7d397cc124ad78c80cd5a8afe1b2e626a3e07643d9c130ac80824e7622edeaeebbd9eafcf96b3509e1b9118e687f62a2cb1e0f15811ca4e1a86fe76566fef4bcc5f6a6d0b55303fb4e951c4a0b8d91e61bf837870f06cf01fde92066fda6f7b71e9299262081f46e26307e073d2070aec30c0ba6d53a0535d78b39dc4ff3da10009243f39a4eb083de724d7af2f35ef1b6d1d11ffa28a7308dd7eeacaa8256a8e8a4e94cce5690c231c614ba01d68f8d096ff1b95b18d95b0e15702d9fadf963992b971b71cbb7b67d764c2439b164a2f846db9c7bdab606028790b4d6947d3f5e9b27cf6471ecc30532302f8cd6e49be45299b4192370952377532cc516d9fb2fae0afc9debd68c7111199fd612f40cf4945b80fc36b648f8f259b96ccce9868f47b37477de152c46b3dc29b7d6616e8de3aff08879726739f9b4c42313023dd3664239cd6cdca4d7c2e24d4feb43cbb1a792197c86cac7ec8ffe34f309641f582e36d90468",
				"enc_session_key": "784b299e4c2e647ee60f11fdb48ea8f3c53c73cc37c59fed4f7a44d3b07c6e874fa9175f997634c7af5789708a5b178a571948620c93c2a281ec6aafd743823835b447d8c853c6f638674329abde5767335d7c098d9ba30ce148fae595d2cda69470da965b98a62704392018a43cf5f2d9b9d724b58a0a4d58e3b33c9df85edad67aa8b7c4cd31ee5c04c3b6176857755239b4a245a453364e21192fff68ace97d84501eaac3cd26198b6e75992ae47e6e1ce5445a22374381c38a3bb09d515e8c160a2a525e07210e7f9d17fc33827aa493fa106969f54a796197a6e2867e82fdf72a4391c52c771920c839ab",
				"tag": "f855cd875160c509951227"
			},
			"type": "object",
			"resource": "gcp_credentials_secret",
			"description": "The GCP Credential use to store data in the gcp_credentials_secret_mirror_n_in bucket"
		},

		"gcp_credentials_secret_bigquery_dlk": {
			"value": {
				"cipher_aes": "f168a6d43280d90b9537",
				"ciphertext": "6cfbb3e058607424704cda5ed389b6fc9ae6650201902ae7ca6c6aa5435fb1cee20680b4564eae60de210564aa2deaef2a7d397cc124ad78c5a97d9dc6bdbf0bb16f37207d6feb1e25e678dd110ed5ae3b4f91765a61747108b7cf8b5a8b7c309e9d403810b6b78adfc08cd3d7e79002a77e4930952377532cc516d9fb2fae0afc9debd68c7111199fd612f40cf4945b80fc36b648f8f259b96ccce9868f47b37477de152c46b3dc29b7d6616e8de3aff08879726739f9b4c42313023dd3664239cd6cdca4d7c2e24d4feb43cbb1a792197c86cac7ec8ffe34f309641f582e36d90468",
				"enc_session_key": "784b299e4389821287ebc4d40dd13179043b021fb38cd54dc53c73cc37c59fed4f7a44d3b07c6e874fa9175f997634c7af5789708a5b178a57194864a796197a6e2867e82fdf72a4391c52c771920c839ab",
				"tag": "f855cd875160c50e5bff3c8c49951227"
			},
			"type": "object",
			"resource": "gcp_credentials_secret",
			"description": "The GCP Credential use to load data in the gcp_project_id_dlk Bigquery"
		}
	}
}
```
Todo : 

- [x] Create a new entry in the left menu bar for "Context". This entry would display a vue component with 2 tabs : Configuration en Documentation (no Run tab)

- [x] Create easy firebase connexion to the firestore collection /tailer-context-conf/

- [x] Load all the documents of the collections filtered for the selected account

- [x] Display in the CONFIGURATION tab the List all those documents. For each rows of the table, show the following information:
  - Account
  - Environment
  - configuration Id (the real configuration_id in the firestore document, not the firestore ID) with a link to the detailed view
  - The "Parameters" number (count the number of object in the parameters map field
  - The status ship (activated or not)

- [x] When clicking on the configuration id link, display the detailed view of the configuration context as the other configuration object
  - Titlte : Configuration Id
  - account
  - environment
  - table with the parameters list in the configuration context
    - fore each row : Name = parameter_key, Value, Type, Resource and description.

### PR DESCRIPTION
**Pull request by Eronne**
## Related issue(s)

Closes #295

## Description

This PR provides new `Context` data workflow.

## What does this PR do?

- [x] Add entry in menu
- [x] Add `vuexeasy-firestore` modules
- [x] Add `ListingView`
- [x] Add `ItemView`

## Deploy notes

Review & merge.

### CODE REVIEW

**Comment by romone22** [comment]
Tests KO: 

The contexts are well visible and implemented in the account jarvis-demo account, but switching in another account to the same context page create an issue 

Uncaught (in promise) TypeError: Cannot read property 'resolve' of undefined
    at y.closeDBChannel (index.esm.js:3702)
    at Array.<anonymous> (vuex.esm.js:851)
    at y.dispatch (vuex.esm.js:516)
    at y.dispatch (vuex.esm.js:406)
    at s.<anonymous> (listing.b4e84456.js:462)
    at f (listing.b4e84456.js:1369)
    at Generator._invoke (listing.b4e84456.js:1586)
    at Generator.next (listing.b4e84456.js:1422)
    at rt (listing.b4e84456.js:375)
    at a (listing.b4e84456.js:377)

I think it's not only for the context but a general easy firestore bug. 

In this case, we have the infinite loading bar. The only way to stop it is to reload the full page

**Comment by romone22** [comment]
Evolution : 
When the object is a Json object, only show the first 50 caracters. 
Adjust the columns to have more space for the others fields. 

image

**Comment by Eronne** [comment]
> Tests KO:
> 
> The contexts are well visible and implemented in the account jarvis-demo account, but switching in another account to the same context page create an issue
> 
> Uncaught (in promise) TypeError: Cannot read property 'resolve' of undefined
> at y.closeDBChannel (index.esm.js:3702)
> at Array. (vuex.esm.js:851)
> at y.dispatch (vuex.esm.js:516)
> at y.dispatch (vuex.esm.js:406)
> at s. (listing.b4e84456.js:462)
> at f (listing.b4e84456.js:1369)
> at Generator._invoke (listing.b4e84456.js:1586)
> at Generator.next (listing.b4e84456.js:1422)
> at rt (listing.b4e84456.js:375)
> at a (listing.b4e84456.js:377)
> 
> I think it's not only for the context but a general easy firestore bug.
> 
> In this case, we have the infinite loading bar. The only way to stop it is to reload the full page

For this problem, we can handle this in a dedicated issue just after this one. If the `context` part is ok, we can merge this PR and treat the `vuex-easy-firestore` issue before releasing the `context` part what do you think?

**Comment by romone22** [comment]
Suppress the Launch bouton. A context can't be launch. It's not a data operation. 

image

**Comment by romone22** [comment]
Est-il aussi possible de mettre un search button pour le tableau pour trouver rapidement un objet dans toutes les colonnes du tableau ?

**Comment by romone22** [comment]
Test OK. Go for merging

**Pull request merged**
