### PR TITLE
Add remote config

### LINKED ISSUE #305: Integrate remote config
**Is your feature request related to a problem? Please describe.**
For the moment, we cannot control feature deployment access depending users.

**Describe the solution you'd like**
Use firebase **remote config** to integrate A/B testing.

**Link**
https://firebase.google.com/docs/remote-config?hl=en&authuser=0

### PR DESCRIPTION
**Pull request by Eronne**
## Related issue(s)

Closes #305 

## Description

This PR provides all necessary configuration for remote config with context. It is developed to integrate further conditions for next features.

## What does this PR do?

- [x] Some refactoring
- [x] Configure remote config
- [x] Create `userCanAccessContexts` rule
- [x] Create middleware for contexts routes 

## Deploy notes

Review & merge.

### CODE REVIEW

**Comment by romone22** [comment]
Question : I should I test this PR ? What is th proecess to test this new features ?

**Comment by Eronne** [comment]
@romone22 yes everything os ready on it

You should not be able to access contexts on an account other than the authorized one in remote confit (which is actually Eram).

**Comment by Eronne** [comment]
I also created a middleware to block non authorized users even if they have the correct URL

**Comment by romone22** [comment]
Hello, I confirm that only the XXX110 account has access. 
But I tried to change this parameters in the remote config console to XXX120. I published the modification but 110 has still access to the context and not 120 ....

**Comment by Eronne** [comment]
Yes it is normal for the actual config 
By default, the remote config is refreshed every 12hours so you will be able to access to context with this new account in 12 hours.

But we can update this value if you want 😉

**Comment by romone22** [comment]
Ah ok. So, for me, the tests are ok

**Comment by romone22** [comment]
We can put that in production

**Comment by Eronne** [comment]
Perfect, I will do it this afternoon 🔥

**Comment by Eronne** [comment]
I didn't see that the branch has been merged directly on `master`. So those changes are available on the production!

**Pull request merged**
